name = "BloodLust";
picture = "mod.paa";
actionName = "Steam Workshop Page";
action = "http://steamcommunity.com/sharedfiles/filedetails/?id=667953829";
description = "Adds more gore to the game.";
logo = "mod.paa";
logoOver = "mod.paa";
tooltip = "BloodLust";
tooltipOwned = "";
overview = "Adds more gore to the game.";
author = "Gavin N. Alvesteffer";
overviewPicture = "mod.paa";
overviewText = "";
