name = "BloodLust";
picture = "mod.paa";
actionName = "NexusMods Page";
action = "https://steamcommunity.com/sharedfiles/filedetails/?id=667953829";
description = "Adds detailed blood and gore effects.";
logo = "mod.paa";
logoOver = "mod.paa";
tooltip = "BloodLust";
tooltipOwned = "";
overview = "Adds detailed blood and gore effects.";
author = "Gavin N. Alvesteffer";
overviewPicture = "mod.paa";
overviewText = "";
