//Blood Lust -- Blood splatter mod.
//Copyright C 2016  Gavin N. Alvesteffer

BloodLust_IsBloodLustEnabled = profileNamespace getVariable ["BloodLust_IsBloodLustEnabled", true];
BloodLust_IsMultiplayerCoreEnabledInSingleplayer = profileNamespace getVariable ["BloodLust_IsMultiplayerCoreEnabledInSingleplayer", false];
BloodLust_IsTexturePreloadingEnabled = profileNamespace getVariable ["BloodLust_IsMultiplayerCoreEnabledInSingleplayer", false];
BloodLust_MaxArterialBloodSprays = profileNamespace getVariable ["BloodLust_MaxArterialBloodSprays", 20];
BloodLust_MaxBloodSprays = profileNamespace getVariable ["BloodLust_MaxBloodSprays", 20];
BloodLust_MaxBloodSplatters                    = profileNamespace getVariable ["BloodLust_MaxBloodSplatters", 1500];
BloodLust_MaxBleedSplatters                    = profileNamespace getVariable ["BloodLust_MaxBleedSplatters", 1500];
BloodLust_MaxGibs                              = profileNamespace getVariable ["BloodLust_MaxGibs", 30];
BloodLust_IsBloodLustEnabledForDeadUnits = profileNamespace getVariable ["BloodLust_IsBloodLustEnabledForDeadUnits", false];
BloodLust_IsFallingVaporizationEnabled = profileNamespace getVariable ["BloodLust_IsFallingVaporizationEnabled", true];
BloodLust_FallingVaporizationSpeedThreshold = profileNamespace getVariable ["BloodLust_FallingVaporizationSpeedThreshold", 20];
BloodLust_FallingVaporizationGibSpeedScalar = profileNamespace getVariable ["BloodLust_FallingVaporizationGibSpeedScalar", 0.2];
BloodLust_IsCleanUpEnabled = profileNamespace getVariable ["BloodLust_IsCleanUpEnabled", true];
BloodLust_CleanUpDistance = profileNamespace getVariable ["BloodLust_CleanUpDistance", 100];
BloodLust_CleanUpDelay = profileNamespace getVariable ["BloodLust_CleanUpDelay", 30];
BloodLust_BloodSplatterProbability = profileNamespace getVariable ["BloodLust_BloodSplatterProbability", 1.0];
BloodLust_BloodSplatterIterationCaliberMultiplier = profileNamespace getVariable ["BloodLust_BloodSplatterIterationCaliberMultiplier", 0.3];
BloodLust_BloodSplatterIterations              = profileNamespace getVariable ["BloodLust_BloodSplatterIterations", 1];
BloodLust_VaporizedBloodSplatterIterations     = profileNamespace getVariable ["BloodLust_VaporizedBloodSplatterIterations", 0];
BloodLust_VaporizedBloodSplatterJitterAmount   = profileNamespace getVariable ["BloodLust_VaporizedBloodSplatterJitterAmount", 10];
BloodLust_VaporizationDamageThreshold          = profileNamespace getVariable ["BloodLust_VaporizationDamageThreshold", 1];
BloodLust_IsVaporizationEnabled                = profileNamespace getVariable ["BloodLust_IsVaporizationEnabled", true];
BloodLust_IsVaporizationEnabledOnPlayer        = profileNamespace getVariable ["BloodLust_IsVaporizationEnabledOnPlayer", true];
BloodLust_BloodSplatterGroundMaxDistance       = profileNamespace getVariable ["BloodLust_BloodSplatterGroundMaxDistance", 1.5];
BloodLust_BloodSplatterIntersectionMaxDistance = profileNamespace getVariable ["BloodLust_BloodSplatterIntersectionMaxDistance", 4];
BloodLust_BloodSplatterJitterAmount            = profileNamespace getVariable ["BloodLust_BloodSplatterJitterAmount", 0];
BloodLust_BloodSplatterAngleJitterAmount = profileNamespace getVariable ["BloodLust_BloodSplatterAngleJitterAmount", 360];
BloodLust_BloodLustActivationDistance          = profileNamespace getVariable ["BloodLust_BloodLustActivationDistance", 2000];
BloodLust_IsBleedingEnabled                    = profileNamespace getVariable ["BloodLust_IsBleedingEnabled", true];
BloodLust_ExplosionDamageThreshold = profileNamespace getVariable ["BloodLust_ExplosionDamageThreshold", 0.2];
BloodLust_ExplosionBloodSplatterIterationMultiplier =  profileNamespace getVariable ["BloodLust_ExplosionBloodSplatterIterationMultiplier", 30];
BloodLust_ExplosionGibForceMultiplier =  profileNamespace getVariable ["BloodLust_ExplosionGibForceMultiplier", 0.3];
BloodLust_BleedDuration                        = profileNamespace getVariable ["BloodLust_BleedDuration", 20];
BloodLust_BleedFrequency                       = profileNamespace getVariable ["BloodLust_BleedFrequency", 0.02];
BloodLust_BleedFrequencyVariance               = profileNamespace getVariable ["BloodLust_BleedFrequencyVariance", 2];
BloodLust_BleedSplatterJitterAmount            = profileNamespace getVariable ["BloodLust_BleedSplatterJitterAmount", 0.15];
BloodLust_BleedSoundAudibleVolume              = profileNamespace getVariable ["BloodLust_BleedSoundAudibleVolume", 4];
BloodLust_BleedSoundAudibleDistance            = profileNamespace getVariable ["BloodLust_BleedSoundAudibleDistance", 10];
BloodLust_BleedSmearSpacing = profileNamespace getVariable ["BloodLust_BleedSmearSpacing", 0.025];
BloodLust_BleedSmearDuration = profileNamespace getVariable ["BloodLust_BleedSmearDuration", 10];
BloodLust_IsBloodSplashingEnabled = profileNamespace getVariable ["BloodLust_IsBloodSplashingEnabled", true];
BloodLust_BloodSplashProjectileSpeedContribution = profileNamespace getVariable ["BloodLust_BloodSplashProjectileSpeedContribution", 0.1];
BloodLust_BloodSplashDuration = profileNamespace getVariable ["BloodLust_BloodSplashDuration", 0.15];
BloodLust_BloodSplashProbability = profileNamespace getVariable ["BloodLust_BloodSplashProbability", 0.8];
BloodLust_BloodSplashMinimumDistanceBetweenDroplets = profileNamespace getVariable ["BloodLust_BloodSplashMinimumDistanceBetweenDroplets", 0.015];
BloodLust_BloodSplashDropletInterval = profileNamespace getVariable ["BloodLust_BloodSplashDropletInterval", 0.001];
BloodLust_BloodSplashDropletsPerIteration = profileNamespace getVariable ["BloodLust_BloodSplashDropletsPerIteration", 3];
BloodLust_BloodSplashDropletTextureSpeedThreshold = profileNamespace getVariable ["BloodLust_BloodSplashDropletTextureSpeedThreshold", 1];
BloodLust_BloodSplashJitterAmount = profileNamespace getVariable ["BloodLust_BloodSplashJitterAmount", 0.3];
BloodLust_IsBloodSprayEnabled = profileNamespace getVariable ["BloodLust_IsBloodSprayEnabled", true];
BloodLust_BloodSprayFramerate = profileNamespace getVariable ["BloodLust_BloodSprayFramerate", 90];
BloodLust_IsBloodPoolingEnabled = profileNamespace getVariable ["BloodLust_IsBloodPoolingEnabled", false];
BloodLust_BloodPoolFramerate = profileNamespace getVariable ["BloodLust_BloodPoolFramerate", 15];
BloodLust_IsArterialBloodSprayEnabled = profileNamespace getVariable ["BloodLust_IsArterialBloodSprayEnabled", true];
BloodLust_ArterialBloodSprayDuration =  profileNamespace getVariable ["BloodLust_ArterialBloodSprayDuration", 10];
BloodLust_ArterialBloodSprayFramerate = profileNamespace getVariable ["BloodLust_ArterialBloodSprayFramerate", 80];
BloodLust_ArterialBloodSprayProbability = profileNamespace getVariable ["BloodLust_ArterialBloodSprayFramerate", 0.75];
BloodLust_BloodSprayProbability = profileNamespace getVariable ["BloodLust_BloodSprayProbability", 0.75];
BloodLust_BloodSprayIterations = profileNamespace getVariable ["BloodLust_BloodSprayIterations", 1];
BloodLust_BloodSpraySoundAudibleVolume              = profileNamespace getVariable ["BloodLust_BloodSpraySoundAudibleVolume", 1.5];
BloodLust_BloodSpraySoundAudibleDistance            = profileNamespace getVariable ["BloodLust_BloodSpraySoundAudibleDistance", 7];
BloodLust_BloodSprayJitterAmount = profileNamespace getVariable ["BloodLust_BloodSprayJitterAmount", 0.25];
BloodLust_IsBloodSpraySoundEnabled = profileNamespace getVariable ["BloodLust_IsBloodSpraySoundEnabled", true];
BloodLust_IsUnitVehicleCollisionEffectsEnabled = profileNamespace getVariable ["BloodLust_IsUnitVehicleCollisionEffectsEnabled", true];
BloodLust_UnitVehicleVaporizationCollisionSpeed = profileNamespace getVariable ["BloodLust_UnitVehicleVaporizationCollisionSpeed", 30];
BloodLust_UnitVehicleVaporizationProbability = profileNamespace getVariable ["BloodLust_UnitVehicleVaporizationProbability", 0.25];
BloodLust_UnitVehicleCollisionBleedDuration = profileNamespace getVariable ["BloodLust_UnitVehicleCollisionBleedDuration", 3];
BloodLust_IsGibbingEnabled                     = profileNamespace getVariable ["BloodLust_IsGibbingEnabled", true];
BloodLust_GibBleedDuration =  profileNamespace getVariable ["BloodLust_GibBleedDuration", 3];
BloodLust_GibCaliberThreshold = profileNamespace getVariable ["BloodLust_GibCaliberThreshold", 0.4];
BloodLust_GibIterations                        = profileNamespace getVariable ["BloodLust_GibIterations", 3];
BloodLust_GibSpeed                             = profileNamespace getVariable ["BloodLust_GibSpeed", 1.75];
BloodLust_GibProbability                       = profileNamespace getVariable ["BloodLust_GibProbability", 0.15];
BloodLust_GibbingProjectileSpeedThreshold      = profileNamespace getVariable ["BloodLust_GibbingProjectileSpeedThreshold", 300];
BloodLust_IsVehicleCrewVaporizationEnabled = profileNamespace getVariable ["BloodLust_IsVehicleCrewVaporizationEnabled", true];
BloodLust_IsVaporizedGibCamSwitchEnabled = profileNamespace getVariable ["BloodLust_IsVaporizedGibCamSwitchEnabled", true];
BloodLust_IsVaporizedHeatWaveEnabled = profileNamespace getVariable ["BloodLust_IsVaporizedHeatWaveEnabled", true];
BloodLust_VaporizationGibIterations            = profileNamespace getVariable ["BloodLust_VaporizationGibIterations", 17];
BloodLust_VaporizationAmmoClassnames           = profileNamespace getVariable ["BloodLust_VaporizationAmmoClassnames",
[
    "MissileCore",
    "RocketCore",
    "TimeBombCore",
    "GrenadeCore",
    "ShellCore",
    "BombCore"
]];
BloodLust_BloodSplatterIntersectionBlackList   = profileNamespace getVariable ["BloodLust_BloodSplatterIntersectionBlackList",
[
    "#particlesource",
    "dummyweapon.p3d",
    "BloodSplatter_Plane",
    "BloodSplatter_SprayPlane",
    "BloodSplatter_MeatChunk_1",
    "BloodSplatter_Brain",
    "WeaponHolderSimulated",
    "WeaponHolder",
    "Thing",
    "Man",
    "AllVehicles",
    "Default"
]];
BloodLust_UnitVehicleCollisionSounds = profileNamespace getVariable ["BloodLust_UnitVehicleCollisionSounds",
[
    "BloodSplatter\Audio\unitvehiclecollision_1.ogg",
    "BloodSplatter\Audio\unitvehiclecollision_2.ogg",
    "BloodSplatter\Audio\unitvehiclecollision_3.ogg",
    "BloodSplatter\Audio\unitvehiclecollision_4.ogg",
    "BloodSplatter\Audio\unitvehiclecollision_5.ogg",
    "BloodSplatter\Audio\unitvehiclecollision_6.ogg",
    "BloodSplatter\Audio\unitvehiclecollision_7.ogg"
]];
BloodLust_VaporizationSounds = profileNamespace getVariable ["BloodLust_VaporizationSounds",
[
    "BloodSplatter\Audio\bodyexplosion_1.ogg",
    "BloodSplatter\Audio\bodyexplosion_2.ogg",
    "BloodSplatter\Audio\bodyexplosion_3.ogg",
    "BloodSplatter\Audio\bodyexplosion_4.ogg",
    "BloodSplatter\Audio\bodyexplosion_5.ogg",
    "BloodSplatter\Audio\bodyexplosion_6.ogg"
]];
BloodLust_BloodSpraySounds = profileNamespace getVariable ["BloodLust_BloodSpraySounds",
[
    "BloodSplatter\Audio\bloodspray_1.ogg",
    "BloodSplatter\Audio\bloodspray_2.ogg",
    "BloodSplatter\Audio\bloodspray_3.ogg",
    "BloodSplatter\Audio\bloodspray_4.ogg",
    "BloodSplatter\Audio\bloodspray_5.ogg",
    "BloodSplatter\Audio\bloodspray_6.ogg"
]];
BloodLust_BloodSplatterSounds = profileNamespace getVariable ["BloodLust_BloodSplatterSounds",
[

]];
BloodLust_HitSounds = profileNamespace getVariable ["BloodLust_HitSounds",
[

]];
BloodLust_HeadSplatterTextures = profileNamespace getVariable ["BloodLust_HeadSplatterTextures", //"head"
[
    [ //Low health.
        "BloodSplatter\Textures\LowHealth\1.paa",
        "BloodSplatter\Textures\LowHealth\2.paa",
        "BloodSplatter\Textures\LowHealth\3.paa",
        "BloodSplatter\Textures\LowHealth\4.paa",
        "BloodSplatter\Textures\LowHealth\5.paa",
        "BloodSplatter\Textures\LowHealth\6.paa",
        "BloodSplatter\Textures\LowHealth\7.paa",
        "BloodSplatter\Textures\LowHealth\8.paa",
        "BloodSplatter\Textures\LowHealth\9.paa",
        "BloodSplatter\Textures\LowHealth\10.paa",
        "BloodSplatter\Textures\LowHealth\11.paa",
        "BloodSplatter\Textures\LowHealth\12.paa",
        "BloodSplatter\Textures\LowHealth\13.paa",
        "BloodSplatter\Textures\LowHealth\14.paa",
        "BloodSplatter\Textures\LowHealth\15.paa",
        "BloodSplatter\Textures\LowHealth\16.paa"
    ],
    [ //Medium health.
        "BloodSplatter\Textures\MediumHealth\1.paa",
        "BloodSplatter\Textures\MediumHealth\2.paa",
        "BloodSplatter\Textures\MediumHealth\3.paa",
        "BloodSplatter\Textures\MediumHealth\4.paa",
        "BloodSplatter\Textures\MediumHealth\5.paa",
        "BloodSplatter\Textures\MediumHealth\6.paa",
        "BloodSplatter\Textures\MediumHealth\7.paa",
        "BloodSplatter\Textures\MediumHealth\8.paa",
        "BloodSplatter\Textures\MediumHealth\9.paa",
        "BloodSplatter\Textures\MediumHealth\10.paa",
        "BloodSplatter\Textures\MediumHealth\11.paa",
        "BloodSplatter\Textures\MediumHealth\12.paa",
        "BloodSplatter\Textures\MediumHealth\13.paa",
        "BloodSplatter\Textures\MediumHealth\14.paa",
        "BloodSplatter\Textures\MediumHealth\15.paa",
        "BloodSplatter\Textures\MediumHealth\16.paa"
    ],
    [ //High health.
        "BloodSplatter\Textures\HighHealth\1.paa",
        "BloodSplatter\Textures\HighHealth\2.paa",
        "BloodSplatter\Textures\HighHealth\3.paa",
        "BloodSplatter\Textures\HighHealth\4.paa",
        "BloodSplatter\Textures\HighHealth\5.paa",
        "BloodSplatter\Textures\HighHealth\6.paa",
        "BloodSplatter\Textures\HighHealth\7.paa",
        "BloodSplatter\Textures\HighHealth\8.paa",
        "BloodSplatter\Textures\HighHealth\9.paa",
        "BloodSplatter\Textures\HighHealth\10.paa",
        "BloodSplatter\Textures\HighHealth\11.paa",
        "BloodSplatter\Textures\HighHealth\12.paa",
        "BloodSplatter\Textures\HighHealth\13.paa",
        "BloodSplatter\Textures\HighHealth\14.paa",
        "BloodSplatter\Textures\HighHealth\15.paa",
        "BloodSplatter\Textures\HighHealth\16.paa"
    ]
]];
BloodLust_Spine1SplatterTextures = profileNamespace getVariable ["BloodLust_Spine1SplatterTextures", //"spine1"
[
    [ //Low health.
        "BloodSplatter\Textures\LowHealth\1.paa",
        "BloodSplatter\Textures\LowHealth\2.paa",
        "BloodSplatter\Textures\LowHealth\3.paa",
        "BloodSplatter\Textures\LowHealth\4.paa",
        "BloodSplatter\Textures\LowHealth\5.paa",
        "BloodSplatter\Textures\LowHealth\6.paa",
        "BloodSplatter\Textures\LowHealth\7.paa",
        "BloodSplatter\Textures\LowHealth\8.paa",
        "BloodSplatter\Textures\LowHealth\9.paa",
        "BloodSplatter\Textures\LowHealth\10.paa",
        "BloodSplatter\Textures\LowHealth\11.paa",
        "BloodSplatter\Textures\LowHealth\12.paa",
        "BloodSplatter\Textures\LowHealth\13.paa",
        "BloodSplatter\Textures\LowHealth\14.paa",
        "BloodSplatter\Textures\LowHealth\15.paa",
        "BloodSplatter\Textures\LowHealth\16.paa"
    ],
    [ //Medium health.
        "BloodSplatter\Textures\MediumHealth\1.paa",
        "BloodSplatter\Textures\MediumHealth\2.paa",
        "BloodSplatter\Textures\MediumHealth\3.paa",
        "BloodSplatter\Textures\MediumHealth\4.paa",
        "BloodSplatter\Textures\MediumHealth\5.paa",
        "BloodSplatter\Textures\MediumHealth\6.paa",
        "BloodSplatter\Textures\MediumHealth\7.paa",
        "BloodSplatter\Textures\MediumHealth\8.paa",
        "BloodSplatter\Textures\MediumHealth\9.paa",
        "BloodSplatter\Textures\MediumHealth\10.paa",
        "BloodSplatter\Textures\MediumHealth\11.paa",
        "BloodSplatter\Textures\MediumHealth\12.paa",
        "BloodSplatter\Textures\MediumHealth\13.paa",
        "BloodSplatter\Textures\MediumHealth\14.paa",
        "BloodSplatter\Textures\MediumHealth\15.paa",
        "BloodSplatter\Textures\MediumHealth\16.paa"
    ],
    [ //High health.
        "BloodSplatter\Textures\HighHealth\1.paa",
        "BloodSplatter\Textures\HighHealth\2.paa",
        "BloodSplatter\Textures\HighHealth\3.paa",
        "BloodSplatter\Textures\HighHealth\4.paa",
        "BloodSplatter\Textures\HighHealth\5.paa",
        "BloodSplatter\Textures\HighHealth\6.paa",
        "BloodSplatter\Textures\HighHealth\7.paa",
        "BloodSplatter\Textures\HighHealth\8.paa",
        "BloodSplatter\Textures\HighHealth\9.paa",
        "BloodSplatter\Textures\HighHealth\10.paa",
        "BloodSplatter\Textures\HighHealth\11.paa",
        "BloodSplatter\Textures\HighHealth\12.paa",
        "BloodSplatter\Textures\HighHealth\13.paa",
        "BloodSplatter\Textures\HighHealth\14.paa",
        "BloodSplatter\Textures\HighHealth\15.paa",
        "BloodSplatter\Textures\HighHealth\16.paa"
    ]
]];
BloodLust_Spine2SplatterTextures = profileNamespace getVariable ["BloodLust_Spine2SplatterTextures", //"spine2"
[
    [ //Low health.
        "BloodSplatter\Textures\LowHealth\1.paa",
        "BloodSplatter\Textures\LowHealth\2.paa",
        "BloodSplatter\Textures\LowHealth\3.paa",
        "BloodSplatter\Textures\LowHealth\4.paa",
        "BloodSplatter\Textures\LowHealth\5.paa",
        "BloodSplatter\Textures\LowHealth\6.paa",
        "BloodSplatter\Textures\LowHealth\7.paa",
        "BloodSplatter\Textures\LowHealth\8.paa",
        "BloodSplatter\Textures\LowHealth\9.paa",
        "BloodSplatter\Textures\LowHealth\10.paa",
        "BloodSplatter\Textures\LowHealth\11.paa",
        "BloodSplatter\Textures\LowHealth\12.paa",
        "BloodSplatter\Textures\LowHealth\13.paa",
        "BloodSplatter\Textures\LowHealth\14.paa",
        "BloodSplatter\Textures\LowHealth\15.paa",
        "BloodSplatter\Textures\LowHealth\16.paa"
    ],
    [ //Medium health.
        "BloodSplatter\Textures\MediumHealth\1.paa",
        "BloodSplatter\Textures\MediumHealth\2.paa",
        "BloodSplatter\Textures\MediumHealth\3.paa",
        "BloodSplatter\Textures\MediumHealth\4.paa",
        "BloodSplatter\Textures\MediumHealth\5.paa",
        "BloodSplatter\Textures\MediumHealth\6.paa",
        "BloodSplatter\Textures\MediumHealth\7.paa",
        "BloodSplatter\Textures\MediumHealth\8.paa",
        "BloodSplatter\Textures\MediumHealth\9.paa",
        "BloodSplatter\Textures\MediumHealth\10.paa",
        "BloodSplatter\Textures\MediumHealth\11.paa",
        "BloodSplatter\Textures\MediumHealth\12.paa",
        "BloodSplatter\Textures\MediumHealth\13.paa",
        "BloodSplatter\Textures\MediumHealth\14.paa",
        "BloodSplatter\Textures\MediumHealth\15.paa",
        "BloodSplatter\Textures\MediumHealth\16.paa"
    ],
    [ //High health.
        "BloodSplatter\Textures\HighHealth\1.paa",
        "BloodSplatter\Textures\HighHealth\2.paa",
        "BloodSplatter\Textures\HighHealth\3.paa",
        "BloodSplatter\Textures\HighHealth\4.paa",
        "BloodSplatter\Textures\HighHealth\5.paa",
        "BloodSplatter\Textures\HighHealth\6.paa",
        "BloodSplatter\Textures\HighHealth\7.paa",
        "BloodSplatter\Textures\HighHealth\8.paa",
        "BloodSplatter\Textures\HighHealth\9.paa",
        "BloodSplatter\Textures\HighHealth\10.paa",
        "BloodSplatter\Textures\HighHealth\11.paa",
        "BloodSplatter\Textures\HighHealth\12.paa",
        "BloodSplatter\Textures\HighHealth\13.paa",
        "BloodSplatter\Textures\HighHealth\14.paa",
        "BloodSplatter\Textures\HighHealth\15.paa",
        "BloodSplatter\Textures\HighHealth\16.paa"
    ]
]];
BloodLust_Spine3SplatterTextures = profileNamespace getVariable ["BloodLust_Spine3SplatterTextures", //"spine3"
[
    [ //Low health.
        "BloodSplatter\Textures\LowHealth\1.paa",
        "BloodSplatter\Textures\LowHealth\2.paa",
        "BloodSplatter\Textures\LowHealth\3.paa",
        "BloodSplatter\Textures\LowHealth\4.paa",
        "BloodSplatter\Textures\LowHealth\5.paa",
        "BloodSplatter\Textures\LowHealth\6.paa",
        "BloodSplatter\Textures\LowHealth\7.paa",
        "BloodSplatter\Textures\LowHealth\8.paa",
        "BloodSplatter\Textures\LowHealth\9.paa",
        "BloodSplatter\Textures\LowHealth\10.paa",
        "BloodSplatter\Textures\LowHealth\11.paa",
        "BloodSplatter\Textures\LowHealth\12.paa",
        "BloodSplatter\Textures\LowHealth\13.paa",
        "BloodSplatter\Textures\LowHealth\14.paa",
        "BloodSplatter\Textures\LowHealth\15.paa",
        "BloodSplatter\Textures\LowHealth\16.paa"
    ],
    [ //Medium health.
        "BloodSplatter\Textures\MediumHealth\1.paa",
        "BloodSplatter\Textures\MediumHealth\2.paa",
        "BloodSplatter\Textures\MediumHealth\3.paa",
        "BloodSplatter\Textures\MediumHealth\4.paa",
        "BloodSplatter\Textures\MediumHealth\5.paa",
        "BloodSplatter\Textures\MediumHealth\6.paa",
        "BloodSplatter\Textures\MediumHealth\7.paa",
        "BloodSplatter\Textures\MediumHealth\8.paa",
        "BloodSplatter\Textures\MediumHealth\9.paa",
        "BloodSplatter\Textures\MediumHealth\10.paa",
        "BloodSplatter\Textures\MediumHealth\11.paa",
        "BloodSplatter\Textures\MediumHealth\12.paa",
        "BloodSplatter\Textures\MediumHealth\13.paa",
        "BloodSplatter\Textures\MediumHealth\14.paa",
        "BloodSplatter\Textures\MediumHealth\15.paa",
        "BloodSplatter\Textures\MediumHealth\16.paa"
    ],
    [ //High health.
        "BloodSplatter\Textures\HighHealth\1.paa",
        "BloodSplatter\Textures\HighHealth\2.paa",
        "BloodSplatter\Textures\HighHealth\3.paa",
        "BloodSplatter\Textures\HighHealth\4.paa",
        "BloodSplatter\Textures\HighHealth\5.paa",
        "BloodSplatter\Textures\HighHealth\6.paa",
        "BloodSplatter\Textures\HighHealth\7.paa",
        "BloodSplatter\Textures\HighHealth\8.paa",
        "BloodSplatter\Textures\HighHealth\9.paa",
        "BloodSplatter\Textures\HighHealth\10.paa",
        "BloodSplatter\Textures\HighHealth\11.paa",
        "BloodSplatter\Textures\HighHealth\12.paa",
        "BloodSplatter\Textures\HighHealth\13.paa",
        "BloodSplatter\Textures\HighHealth\14.paa",
        "BloodSplatter\Textures\HighHealth\15.paa",
        "BloodSplatter\Textures\HighHealth\16.paa"
    ]
]];
BloodLust_BodySplatterTextures = profileNamespace getVariable ["BloodLust_BodySplatterTextures", //"body"
[
    [ //Low health.
        "BloodSplatter\Textures\LowHealth\1.paa",
        "BloodSplatter\Textures\LowHealth\2.paa",
        "BloodSplatter\Textures\LowHealth\3.paa",
        "BloodSplatter\Textures\LowHealth\4.paa",
        "BloodSplatter\Textures\LowHealth\5.paa",
        "BloodSplatter\Textures\LowHealth\6.paa",
        "BloodSplatter\Textures\LowHealth\7.paa",
        "BloodSplatter\Textures\LowHealth\8.paa",
        "BloodSplatter\Textures\LowHealth\9.paa",
        "BloodSplatter\Textures\LowHealth\10.paa",
        "BloodSplatter\Textures\LowHealth\11.paa",
        "BloodSplatter\Textures\LowHealth\12.paa",
        "BloodSplatter\Textures\LowHealth\13.paa",
        "BloodSplatter\Textures\LowHealth\14.paa",
        "BloodSplatter\Textures\LowHealth\15.paa",
        "BloodSplatter\Textures\LowHealth\16.paa"
    ],
    [ //Medium health.
        "BloodSplatter\Textures\MediumHealth\1.paa",
        "BloodSplatter\Textures\MediumHealth\2.paa",
        "BloodSplatter\Textures\MediumHealth\3.paa",
        "BloodSplatter\Textures\MediumHealth\4.paa",
        "BloodSplatter\Textures\MediumHealth\5.paa",
        "BloodSplatter\Textures\MediumHealth\6.paa",
        "BloodSplatter\Textures\MediumHealth\7.paa",
        "BloodSplatter\Textures\MediumHealth\8.paa",
        "BloodSplatter\Textures\MediumHealth\9.paa",
        "BloodSplatter\Textures\MediumHealth\10.paa",
        "BloodSplatter\Textures\MediumHealth\11.paa",
        "BloodSplatter\Textures\MediumHealth\12.paa",
        "BloodSplatter\Textures\MediumHealth\13.paa",
        "BloodSplatter\Textures\MediumHealth\14.paa",
        "BloodSplatter\Textures\MediumHealth\15.paa",
        "BloodSplatter\Textures\MediumHealth\16.paa"
    ],
    [ //High health.
        "BloodSplatter\Textures\HighHealth\1.paa",
        "BloodSplatter\Textures\HighHealth\2.paa",
        "BloodSplatter\Textures\HighHealth\3.paa",
        "BloodSplatter\Textures\HighHealth\4.paa",
        "BloodSplatter\Textures\HighHealth\5.paa",
        "BloodSplatter\Textures\HighHealth\6.paa",
        "BloodSplatter\Textures\HighHealth\7.paa",
        "BloodSplatter\Textures\HighHealth\8.paa",
        "BloodSplatter\Textures\HighHealth\9.paa",
        "BloodSplatter\Textures\HighHealth\10.paa",
        "BloodSplatter\Textures\HighHealth\11.paa",
        "BloodSplatter\Textures\HighHealth\12.paa",
        "BloodSplatter\Textures\HighHealth\13.paa",
        "BloodSplatter\Textures\HighHealth\14.paa",
        "BloodSplatter\Textures\HighHealth\15.paa",
        "BloodSplatter\Textures\HighHealth\16.paa"
    ]
]];
BloodLust_ArmSplatterTextures = profileNamespace getVariable ["BloodLust_ArmSplatterTextures", //"arms"
[
    [ //Low health.
        "BloodSplatter\Textures\LowHealth\1.paa",
        "BloodSplatter\Textures\LowHealth\2.paa",
        "BloodSplatter\Textures\LowHealth\3.paa",
        "BloodSplatter\Textures\LowHealth\4.paa",
        "BloodSplatter\Textures\LowHealth\5.paa",
        "BloodSplatter\Textures\LowHealth\6.paa",
        "BloodSplatter\Textures\LowHealth\7.paa",
        "BloodSplatter\Textures\LowHealth\8.paa",
        "BloodSplatter\Textures\LowHealth\9.paa",
        "BloodSplatter\Textures\LowHealth\10.paa",
        "BloodSplatter\Textures\LowHealth\11.paa",
        "BloodSplatter\Textures\LowHealth\12.paa",
        "BloodSplatter\Textures\LowHealth\13.paa",
        "BloodSplatter\Textures\LowHealth\14.paa",
        "BloodSplatter\Textures\LowHealth\15.paa",
        "BloodSplatter\Textures\LowHealth\16.paa"
    ],
    [ //Medium health.
        "BloodSplatter\Textures\MediumHealth\1.paa",
        "BloodSplatter\Textures\MediumHealth\2.paa",
        "BloodSplatter\Textures\MediumHealth\3.paa",
        "BloodSplatter\Textures\MediumHealth\4.paa",
        "BloodSplatter\Textures\MediumHealth\5.paa",
        "BloodSplatter\Textures\MediumHealth\6.paa",
        "BloodSplatter\Textures\MediumHealth\7.paa",
        "BloodSplatter\Textures\MediumHealth\8.paa",
        "BloodSplatter\Textures\MediumHealth\9.paa",
        "BloodSplatter\Textures\MediumHealth\10.paa",
        "BloodSplatter\Textures\MediumHealth\11.paa",
        "BloodSplatter\Textures\MediumHealth\12.paa",
        "BloodSplatter\Textures\MediumHealth\13.paa",
        "BloodSplatter\Textures\MediumHealth\14.paa",
        "BloodSplatter\Textures\MediumHealth\15.paa",
        "BloodSplatter\Textures\MediumHealth\16.paa"
    ],
    [ //High health.
        "BloodSplatter\Textures\HighHealth\1.paa",
        "BloodSplatter\Textures\HighHealth\2.paa",
        "BloodSplatter\Textures\HighHealth\3.paa",
        "BloodSplatter\Textures\HighHealth\4.paa",
        "BloodSplatter\Textures\HighHealth\5.paa",
        "BloodSplatter\Textures\HighHealth\6.paa",
        "BloodSplatter\Textures\HighHealth\7.paa",
        "BloodSplatter\Textures\HighHealth\8.paa",
        "BloodSplatter\Textures\HighHealth\9.paa",
        "BloodSplatter\Textures\HighHealth\10.paa",
        "BloodSplatter\Textures\HighHealth\11.paa",
        "BloodSplatter\Textures\HighHealth\12.paa",
        "BloodSplatter\Textures\HighHealth\13.paa",
        "BloodSplatter\Textures\HighHealth\14.paa",
        "BloodSplatter\Textures\HighHealth\15.paa",
        "BloodSplatter\Textures\HighHealth\16.paa"
    ]
]];
BloodLust_LegSplatterTextures = profileNamespace getVariable ["BloodLust_LegSplatterTextures", //"legs"
[
    [ //Low health.
        "BloodSplatter\Textures\LowHealth\1.paa",
        "BloodSplatter\Textures\LowHealth\2.paa",
        "BloodSplatter\Textures\LowHealth\3.paa",
        "BloodSplatter\Textures\LowHealth\4.paa",
        "BloodSplatter\Textures\LowHealth\5.paa",
        "BloodSplatter\Textures\LowHealth\6.paa",
        "BloodSplatter\Textures\LowHealth\7.paa",
        "BloodSplatter\Textures\LowHealth\8.paa",
        "BloodSplatter\Textures\LowHealth\9.paa",
        "BloodSplatter\Textures\LowHealth\10.paa",
        "BloodSplatter\Textures\LowHealth\11.paa",
        "BloodSplatter\Textures\LowHealth\12.paa",
        "BloodSplatter\Textures\LowHealth\13.paa",
        "BloodSplatter\Textures\LowHealth\14.paa",
        "BloodSplatter\Textures\LowHealth\15.paa",
        "BloodSplatter\Textures\LowHealth\16.paa"
    ],
    [ //Medium health.
        "BloodSplatter\Textures\MediumHealth\1.paa",
        "BloodSplatter\Textures\MediumHealth\2.paa",
        "BloodSplatter\Textures\MediumHealth\3.paa",
        "BloodSplatter\Textures\MediumHealth\4.paa",
        "BloodSplatter\Textures\MediumHealth\5.paa",
        "BloodSplatter\Textures\MediumHealth\6.paa",
        "BloodSplatter\Textures\MediumHealth\7.paa",
        "BloodSplatter\Textures\MediumHealth\8.paa",
        "BloodSplatter\Textures\MediumHealth\9.paa",
        "BloodSplatter\Textures\MediumHealth\10.paa",
        "BloodSplatter\Textures\MediumHealth\11.paa",
        "BloodSplatter\Textures\MediumHealth\12.paa",
        "BloodSplatter\Textures\MediumHealth\13.paa",
        "BloodSplatter\Textures\MediumHealth\14.paa",
        "BloodSplatter\Textures\MediumHealth\15.paa",
        "BloodSplatter\Textures\MediumHealth\16.paa"
    ],
    [ //High health.
        "BloodSplatter\Textures\HighHealth\1.paa",
        "BloodSplatter\Textures\HighHealth\2.paa",
        "BloodSplatter\Textures\HighHealth\3.paa",
        "BloodSplatter\Textures\HighHealth\4.paa",
        "BloodSplatter\Textures\HighHealth\5.paa",
        "BloodSplatter\Textures\HighHealth\6.paa",
        "BloodSplatter\Textures\HighHealth\7.paa",
        "BloodSplatter\Textures\HighHealth\8.paa",
        "BloodSplatter\Textures\HighHealth\9.paa",
        "BloodSplatter\Textures\HighHealth\10.paa",
        "BloodSplatter\Textures\HighHealth\11.paa",
        "BloodSplatter\Textures\HighHealth\12.paa",
        "BloodSplatter\Textures\HighHealth\13.paa",
        "BloodSplatter\Textures\HighHealth\14.paa",
        "BloodSplatter\Textures\HighHealth\15.paa",
        "BloodSplatter\Textures\HighHealth\16.paa"
    ]
]];
BloodLust_LargeVaporizationBloodSplatters = profileNamespace getVariable ["BloodLust_LargeVaporizationBloodSplatters",
[
    "BloodSplatter\Textures\Vaporization\1.paa",
    "BloodSplatter\Textures\Vaporization\2.paa",
    "BloodSplatter\Textures\Vaporization\3.paa",
    "BloodSplatter\Textures\Vaporization\4.paa"
]];
BloodLust_VaporizationBloodSplatters = profileNamespace getVariable ["BloodLust_VaporizationBloodSplatters",
[
    "BloodSplatter\Textures\LowHealth\1.paa",
    "BloodSplatter\Textures\LowHealth\2.paa",
    "BloodSplatter\Textures\LowHealth\3.paa",
    "BloodSplatter\Textures\LowHealth\4.paa",
    "BloodSplatter\Textures\LowHealth\5.paa",
    "BloodSplatter\Textures\LowHealth\6.paa",
    "BloodSplatter\Textures\LowHealth\7.paa",
    "BloodSplatter\Textures\LowHealth\8.paa",
    "BloodSplatter\Textures\LowHealth\9.paa",
    "BloodSplatter\Textures\LowHealth\10.paa",
    "BloodSplatter\Textures\LowHealth\11.paa",
    "BloodSplatter\Textures\LowHealth\12.paa",
    "BloodSplatter\Textures\LowHealth\13.paa",
    "BloodSplatter\Textures\LowHealth\14.paa",
    "BloodSplatter\Textures\LowHealth\15.paa",
    "BloodSplatter\Textures\LowHealth\16.paa",
    "BloodSplatter\Textures\MediumHealth\1.paa",
    "BloodSplatter\Textures\MediumHealth\2.paa",
    "BloodSplatter\Textures\MediumHealth\3.paa",
    "BloodSplatter\Textures\MediumHealth\4.paa",
    "BloodSplatter\Textures\MediumHealth\5.paa",
    "BloodSplatter\Textures\MediumHealth\6.paa",
    "BloodSplatter\Textures\MediumHealth\7.paa",
    "BloodSplatter\Textures\MediumHealth\8.paa",
    "BloodSplatter\Textures\MediumHealth\9.paa",
    "BloodSplatter\Textures\MediumHealth\10.paa",
    "BloodSplatter\Textures\MediumHealth\11.paa",
    "BloodSplatter\Textures\MediumHealth\12.paa",
    "BloodSplatter\Textures\MediumHealth\13.paa",
    "BloodSplatter\Textures\MediumHealth\14.paa",
    "BloodSplatter\Textures\MediumHealth\15.paa",
    "BloodSplatter\Textures\MediumHealth\16.paa",
    "BloodSplatter\Textures\HighHealth\1.paa",
    "BloodSplatter\Textures\HighHealth\2.paa",
    "BloodSplatter\Textures\HighHealth\3.paa",
    "BloodSplatter\Textures\HighHealth\4.paa",
    "BloodSplatter\Textures\HighHealth\5.paa",
    "BloodSplatter\Textures\HighHealth\6.paa",
    "BloodSplatter\Textures\HighHealth\7.paa",
    "BloodSplatter\Textures\HighHealth\8.paa",
    "BloodSplatter\Textures\HighHealth\9.paa",
    "BloodSplatter\Textures\HighHealth\10.paa",
    "BloodSplatter\Textures\HighHealth\11.paa",
    "BloodSplatter\Textures\HighHealth\12.paa",
    "BloodSplatter\Textures\HighHealth\13.paa",
    "BloodSplatter\Textures\HighHealth\14.paa",
    "BloodSplatter\Textures\HighHealth\15.paa",
    "BloodSplatter\Textures\HighHealth\16.paa",
    "BloodSplatter\Textures\Bleed\bleed_1.paa",
    "BloodSplatter\Textures\Bleed\bleed_2.paa",
    "BloodSplatter\Textures\Bleed\bleed_3.paa",
    "BloodSplatter\Textures\Bleed\bleed_4.paa",
    "BloodSplatter\Textures\Bleed\bleed_5.paa",
    "BloodSplatter\Textures\Bleed\bleed_6.paa",
    "BloodSplatter\Textures\Bleed\bleed_7.paa",
    "BloodSplatter\Textures\Bleed\bleed_8.paa",
    "BloodSplatter\Textures\Bleed\bleed_9.paa",
    "BloodSplatter\Textures\Bleed\bleed_10.paa",
    "BloodSplatter\Textures\Bleed\bleed_11.paa",
    "BloodSplatter\Textures\Bleed\bleed_12.paa",
    "BloodSplatter\Textures\Smear\smear_1.paa",
    "BloodSplatter\Textures\Smear\smear_2.paa",
    "BloodSplatter\Textures\Smear\smear_3.paa",
    "BloodSplatter\Textures\Smear\smear_4.paa",
    "BloodSplatter\Textures\Smear\smear_5.paa",
    "BloodSplatter\Textures\Smear\smear_6.paa",
    "BloodSplatter\Textures\Smear\smear_7.paa",
    "BloodSplatter\Textures\Smear\smear_8.paa"
]];
BloodLust_BloodPoolTextures = profileNamespace getVariable ["BloodLust_BloodPoolTextures",
[
    [
        "BloodSplatter\Textures\BloodPool_1\1.paa",
        "BloodSplatter\Textures\BloodPool_1\2.paa",
        "BloodSplatter\Textures\BloodPool_1\3.paa",
        "BloodSplatter\Textures\BloodPool_1\4.paa",
        "BloodSplatter\Textures\BloodPool_1\5.paa",
        "BloodSplatter\Textures\BloodPool_1\6.paa",
        "BloodSplatter\Textures\BloodPool_1\7.paa",
        "BloodSplatter\Textures\BloodPool_1\8.paa",
        "BloodSplatter\Textures\BloodPool_1\9.paa",
        "BloodSplatter\Textures\BloodPool_1\10.paa",
        "BloodSplatter\Textures\BloodPool_1\11.paa",
        "BloodSplatter\Textures\BloodPool_1\12.paa",
        "BloodSplatter\Textures\BloodPool_1\13.paa",
        "BloodSplatter\Textures\BloodPool_1\14.paa",
        "BloodSplatter\Textures\BloodPool_1\15.paa",
        "BloodSplatter\Textures\BloodPool_1\16.paa",
        "BloodSplatter\Textures\BloodPool_1\17.paa",
        "BloodSplatter\Textures\BloodPool_1\18.paa",
        "BloodSplatter\Textures\BloodPool_1\19.paa",
        "BloodSplatter\Textures\BloodPool_1\20.paa",
        "BloodSplatter\Textures\BloodPool_1\21.paa",
        "BloodSplatter\Textures\BloodPool_1\22.paa",
        "BloodSplatter\Textures\BloodPool_1\23.paa",
        "BloodSplatter\Textures\BloodPool_1\24.paa",
        "BloodSplatter\Textures\BloodPool_1\25.paa",
        "BloodSplatter\Textures\BloodPool_1\26.paa",
        "BloodSplatter\Textures\BloodPool_1\27.paa",
        "BloodSplatter\Textures\BloodPool_1\28.paa",
        "BloodSplatter\Textures\BloodPool_1\29.paa",
        "BloodSplatter\Textures\BloodPool_1\30.paa",
        "BloodSplatter\Textures\BloodPool_1\31.paa",
        "BloodSplatter\Textures\BloodPool_1\32.paa",
        "BloodSplatter\Textures\BloodPool_1\33.paa",
        "BloodSplatter\Textures\BloodPool_1\34.paa",
        "BloodSplatter\Textures\BloodPool_1\35.paa",
        "BloodSplatter\Textures\BloodPool_1\36.paa",
        "BloodSplatter\Textures\BloodPool_1\37.paa",
        "BloodSplatter\Textures\BloodPool_1\38.paa",
        "BloodSplatter\Textures\BloodPool_1\39.paa",
        "BloodSplatter\Textures\BloodPool_1\40.paa",
        "BloodSplatter\Textures\BloodPool_1\41.paa",
        "BloodSplatter\Textures\BloodPool_1\42.paa",
        "BloodSplatter\Textures\BloodPool_1\43.paa",
        "BloodSplatter\Textures\BloodPool_1\44.paa",
        "BloodSplatter\Textures\BloodPool_1\45.paa",
        "BloodSplatter\Textures\BloodPool_1\46.paa",
        "BloodSplatter\Textures\BloodPool_1\47.paa",
        "BloodSplatter\Textures\BloodPool_1\48.paa",
        "BloodSplatter\Textures\BloodPool_1\49.paa",
        "BloodSplatter\Textures\BloodPool_1\50.paa",
        "BloodSplatter\Textures\BloodPool_1\51.paa",
        "BloodSplatter\Textures\BloodPool_1\52.paa",
        "BloodSplatter\Textures\BloodPool_1\53.paa",
        "BloodSplatter\Textures\BloodPool_1\54.paa",
        "BloodSplatter\Textures\BloodPool_1\55.paa",
        "BloodSplatter\Textures\BloodPool_1\56.paa",
        "BloodSplatter\Textures\BloodPool_1\57.paa",
        "BloodSplatter\Textures\BloodPool_1\58.paa",
        "BloodSplatter\Textures\BloodPool_1\59.paa",
        "BloodSplatter\Textures\BloodPool_1\60.paa",
        "BloodSplatter\Textures\BloodPool_1\61.paa",
        "BloodSplatter\Textures\BloodPool_1\62.paa",
        "BloodSplatter\Textures\BloodPool_1\63.paa",
        "BloodSplatter\Textures\BloodPool_1\64.paa",
        "BloodSplatter\Textures\BloodPool_1\65.paa",
        "BloodSplatter\Textures\BloodPool_1\66.paa",
        "BloodSplatter\Textures\BloodPool_1\67.paa",
        "BloodSplatter\Textures\BloodPool_1\68.paa",
        "BloodSplatter\Textures\BloodPool_1\69.paa",
        "BloodSplatter\Textures\BloodPool_1\70.paa",
        "BloodSplatter\Textures\BloodPool_1\71.paa",
        "BloodSplatter\Textures\BloodPool_1\72.paa",
        "BloodSplatter\Textures\BloodPool_1\73.paa",
        "BloodSplatter\Textures\BloodPool_1\74.paa",
        "BloodSplatter\Textures\BloodPool_1\75.paa",
        "BloodSplatter\Textures\BloodPool_1\76.paa",
        "BloodSplatter\Textures\BloodPool_1\77.paa",
        "BloodSplatter\Textures\BloodPool_1\78.paa",
        "BloodSplatter\Textures\BloodPool_1\79.paa",
        "BloodSplatter\Textures\BloodPool_1\80.paa",
        "BloodSplatter\Textures\BloodPool_1\81.paa",
        "BloodSplatter\Textures\BloodPool_1\82.paa",
        "BloodSplatter\Textures\BloodPool_1\83.paa",
        "BloodSplatter\Textures\BloodPool_1\84.paa",
        "BloodSplatter\Textures\BloodPool_1\85.paa",
        "BloodSplatter\Textures\BloodPool_1\86.paa",
        "BloodSplatter\Textures\BloodPool_1\87.paa",
        "BloodSplatter\Textures\BloodPool_1\88.paa",
        "BloodSplatter\Textures\BloodPool_1\89.paa",
        "BloodSplatter\Textures\BloodPool_1\90.paa",
        "BloodSplatter\Textures\BloodPool_1\91.paa",
        "BloodSplatter\Textures\BloodPool_1\92.paa",
        "BloodSplatter\Textures\BloodPool_1\93.paa",
        "BloodSplatter\Textures\BloodPool_1\94.paa",
        "BloodSplatter\Textures\BloodPool_1\95.paa",
        "BloodSplatter\Textures\BloodPool_1\96.paa",
        "BloodSplatter\Textures\BloodPool_1\97.paa",
        "BloodSplatter\Textures\BloodPool_1\98.paa",
        "BloodSplatter\Textures\BloodPool_1\99.paa",
        "BloodSplatter\Textures\BloodPool_1\100.paa",
        "BloodSplatter\Textures\BloodPool_1\101.paa",
        "BloodSplatter\Textures\BloodPool_1\102.paa",
        "BloodSplatter\Textures\BloodPool_1\103.paa",
        "BloodSplatter\Textures\BloodPool_1\104.paa",
        "BloodSplatter\Textures\BloodPool_1\105.paa",
        "BloodSplatter\Textures\BloodPool_1\106.paa",
        "BloodSplatter\Textures\BloodPool_1\107.paa",
        "BloodSplatter\Textures\BloodPool_1\108.paa",
        "BloodSplatter\Textures\BloodPool_1\109.paa",
        "BloodSplatter\Textures\BloodPool_1\110.paa",
        "BloodSplatter\Textures\BloodPool_1\111.paa",
        "BloodSplatter\Textures\BloodPool_1\112.paa",
        "BloodSplatter\Textures\BloodPool_1\113.paa",
        "BloodSplatter\Textures\BloodPool_1\114.paa",
        "BloodSplatter\Textures\BloodPool_1\115.paa",
        "BloodSplatter\Textures\BloodPool_1\116.paa",
        "BloodSplatter\Textures\BloodPool_1\117.paa",
        "BloodSplatter\Textures\BloodPool_1\118.paa",
        "BloodSplatter\Textures\BloodPool_1\119.paa",
        "BloodSplatter\Textures\BloodPool_1\120.paa",
        "BloodSplatter\Textures\BloodPool_1\121.paa",
        "BloodSplatter\Textures\BloodPool_1\122.paa",
        "BloodSplatter\Textures\BloodPool_1\123.paa",
        "BloodSplatter\Textures\BloodPool_1\124.paa",
        "BloodSplatter\Textures\BloodPool_1\125.paa",
        "BloodSplatter\Textures\BloodPool_1\126.paa",
        "BloodSplatter\Textures\BloodPool_1\127.paa",
        "BloodSplatter\Textures\BloodPool_1\128.paa",
        "BloodSplatter\Textures\BloodPool_1\129.paa",
        "BloodSplatter\Textures\BloodPool_1\130.paa",
        "BloodSplatter\Textures\BloodPool_1\131.paa",
        "BloodSplatter\Textures\BloodPool_1\132.paa",
        "BloodSplatter\Textures\BloodPool_1\133.paa",
        "BloodSplatter\Textures\BloodPool_1\134.paa",
        "BloodSplatter\Textures\BloodPool_1\135.paa",
        "BloodSplatter\Textures\BloodPool_1\136.paa",
        "BloodSplatter\Textures\BloodPool_1\137.paa",
        "BloodSplatter\Textures\BloodPool_1\138.paa",
        "BloodSplatter\Textures\BloodPool_1\139.paa",
        "BloodSplatter\Textures\BloodPool_1\140.paa",
        "BloodSplatter\Textures\BloodPool_1\141.paa",
        "BloodSplatter\Textures\BloodPool_1\142.paa",
        "BloodSplatter\Textures\BloodPool_1\143.paa",
        "BloodSplatter\Textures\BloodPool_1\144.paa",
        "BloodSplatter\Textures\BloodPool_1\145.paa",
        "BloodSplatter\Textures\BloodPool_1\146.paa",
        "BloodSplatter\Textures\BloodPool_1\147.paa",
        "BloodSplatter\Textures\BloodPool_1\148.paa",
        "BloodSplatter\Textures\BloodPool_1\149.paa",
        "BloodSplatter\Textures\BloodPool_1\150.paa",
        "BloodSplatter\Textures\BloodPool_1\151.paa",
        "BloodSplatter\Textures\BloodPool_1\152.paa",
        "BloodSplatter\Textures\BloodPool_1\153.paa",
        "BloodSplatter\Textures\BloodPool_1\154.paa",
        "BloodSplatter\Textures\BloodPool_1\155.paa",
        "BloodSplatter\Textures\BloodPool_1\156.paa",
        "BloodSplatter\Textures\BloodPool_1\157.paa",
        "BloodSplatter\Textures\BloodPool_1\158.paa",
        "BloodSplatter\Textures\BloodPool_1\159.paa",
        "BloodSplatter\Textures\BloodPool_1\160.paa",
        "BloodSplatter\Textures\BloodPool_1\161.paa",
        "BloodSplatter\Textures\BloodPool_1\162.paa",
        "BloodSplatter\Textures\BloodPool_1\163.paa",
        "BloodSplatter\Textures\BloodPool_1\164.paa",
        "BloodSplatter\Textures\BloodPool_1\165.paa",
        "BloodSplatter\Textures\BloodPool_1\166.paa",
        "BloodSplatter\Textures\BloodPool_1\167.paa",
        "BloodSplatter\Textures\BloodPool_1\168.paa",
        "BloodSplatter\Textures\BloodPool_1\169.paa",
        "BloodSplatter\Textures\BloodPool_1\170.paa",
        "BloodSplatter\Textures\BloodPool_1\171.paa",
        "BloodSplatter\Textures\BloodPool_1\172.paa",
        "BloodSplatter\Textures\BloodPool_1\173.paa",
        "BloodSplatter\Textures\BloodPool_1\174.paa",
        "BloodSplatter\Textures\BloodPool_1\175.paa",
        "BloodSplatter\Textures\BloodPool_1\176.paa",
        "BloodSplatter\Textures\BloodPool_1\177.paa",
        "BloodSplatter\Textures\BloodPool_1\178.paa",
        "BloodSplatter\Textures\BloodPool_1\179.paa",
        "BloodSplatter\Textures\BloodPool_1\180.paa",
        "BloodSplatter\Textures\BloodPool_1\181.paa",
        "BloodSplatter\Textures\BloodPool_1\182.paa",
        "BloodSplatter\Textures\BloodPool_1\183.paa",
        "BloodSplatter\Textures\BloodPool_1\184.paa",
        "BloodSplatter\Textures\BloodPool_1\185.paa",
        "BloodSplatter\Textures\BloodPool_1\186.paa",
        "BloodSplatter\Textures\BloodPool_1\187.paa",
        "BloodSplatter\Textures\BloodPool_1\188.paa",
        "BloodSplatter\Textures\BloodPool_1\189.paa",
        "BloodSplatter\Textures\BloodPool_1\190.paa",
        "BloodSplatter\Textures\BloodPool_1\191.paa",
        "BloodSplatter\Textures\BloodPool_1\192.paa",
        "BloodSplatter\Textures\BloodPool_1\193.paa",
        "BloodSplatter\Textures\BloodPool_1\194.paa",
        "BloodSplatter\Textures\BloodPool_1\195.paa",
        "BloodSplatter\Textures\BloodPool_1\196.paa",
        "BloodSplatter\Textures\BloodPool_1\197.paa",
        "BloodSplatter\Textures\BloodPool_1\198.paa",
        "BloodSplatter\Textures\BloodPool_1\199.paa",
        "BloodSplatter\Textures\BloodPool_1\200.paa",
        "BloodSplatter\Textures\BloodPool_1\201.paa",
        "BloodSplatter\Textures\BloodPool_1\202.paa",
        "BloodSplatter\Textures\BloodPool_1\203.paa",
        "BloodSplatter\Textures\BloodPool_1\204.paa",
        "BloodSplatter\Textures\BloodPool_1\205.paa",
        "BloodSplatter\Textures\BloodPool_1\206.paa",
        "BloodSplatter\Textures\BloodPool_1\207.paa",
        "BloodSplatter\Textures\BloodPool_1\208.paa",
        "BloodSplatter\Textures\BloodPool_1\209.paa",
        "BloodSplatter\Textures\BloodPool_1\210.paa",
        "BloodSplatter\Textures\BloodPool_1\211.paa",
        "BloodSplatter\Textures\BloodPool_1\212.paa",
        "BloodSplatter\Textures\BloodPool_1\213.paa",
        "BloodSplatter\Textures\BloodPool_1\214.paa",
        "BloodSplatter\Textures\BloodPool_1\215.paa",
        "BloodSplatter\Textures\BloodPool_1\216.paa",
        "BloodSplatter\Textures\BloodPool_1\217.paa",
        "BloodSplatter\Textures\BloodPool_1\218.paa",
        "BloodSplatter\Textures\BloodPool_1\219.paa",
        "BloodSplatter\Textures\BloodPool_1\220.paa",
        "BloodSplatter\Textures\BloodPool_1\221.paa",
        "BloodSplatter\Textures\BloodPool_1\222.paa",
        "BloodSplatter\Textures\BloodPool_1\223.paa",
        "BloodSplatter\Textures\BloodPool_1\224.paa",
        "BloodSplatter\Textures\BloodPool_1\225.paa",
        "BloodSplatter\Textures\BloodPool_1\226.paa",
        "BloodSplatter\Textures\BloodPool_1\227.paa",
        "BloodSplatter\Textures\BloodPool_1\228.paa",
        "BloodSplatter\Textures\BloodPool_1\229.paa"
    ],
    [
        "BloodSplatter\Textures\BloodPool_2\0.paa",
        "BloodSplatter\Textures\BloodPool_2\1.paa",
        "BloodSplatter\Textures\BloodPool_2\2.paa",
        "BloodSplatter\Textures\BloodPool_2\3.paa",
        "BloodSplatter\Textures\BloodPool_2\4.paa",
        "BloodSplatter\Textures\BloodPool_2\5.paa",
        "BloodSplatter\Textures\BloodPool_2\6.paa",
        "BloodSplatter\Textures\BloodPool_2\7.paa",
        "BloodSplatter\Textures\BloodPool_2\8.paa",
        "BloodSplatter\Textures\BloodPool_2\9.paa",
        "BloodSplatter\Textures\BloodPool_2\10.paa",
        "BloodSplatter\Textures\BloodPool_2\11.paa",
        "BloodSplatter\Textures\BloodPool_2\12.paa",
        "BloodSplatter\Textures\BloodPool_2\13.paa",
        "BloodSplatter\Textures\BloodPool_2\14.paa",
        "BloodSplatter\Textures\BloodPool_2\15.paa",
        "BloodSplatter\Textures\BloodPool_2\16.paa",
        "BloodSplatter\Textures\BloodPool_2\17.paa",
        "BloodSplatter\Textures\BloodPool_2\18.paa",
        "BloodSplatter\Textures\BloodPool_2\19.paa",
        "BloodSplatter\Textures\BloodPool_2\20.paa",
        "BloodSplatter\Textures\BloodPool_2\21.paa",
        "BloodSplatter\Textures\BloodPool_2\22.paa",
        "BloodSplatter\Textures\BloodPool_2\23.paa",
        "BloodSplatter\Textures\BloodPool_2\24.paa",
        "BloodSplatter\Textures\BloodPool_2\25.paa",
        "BloodSplatter\Textures\BloodPool_2\26.paa",
        "BloodSplatter\Textures\BloodPool_2\27.paa",
        "BloodSplatter\Textures\BloodPool_2\28.paa",
        "BloodSplatter\Textures\BloodPool_2\29.paa",
        "BloodSplatter\Textures\BloodPool_2\30.paa",
        "BloodSplatter\Textures\BloodPool_2\31.paa",
        "BloodSplatter\Textures\BloodPool_2\32.paa",
        "BloodSplatter\Textures\BloodPool_2\33.paa",
        "BloodSplatter\Textures\BloodPool_2\34.paa",
        "BloodSplatter\Textures\BloodPool_2\35.paa",
        "BloodSplatter\Textures\BloodPool_2\36.paa",
        "BloodSplatter\Textures\BloodPool_2\37.paa",
        "BloodSplatter\Textures\BloodPool_2\38.paa",
        "BloodSplatter\Textures\BloodPool_2\39.paa",
        "BloodSplatter\Textures\BloodPool_2\40.paa",
        "BloodSplatter\Textures\BloodPool_2\41.paa",
        "BloodSplatter\Textures\BloodPool_2\42.paa",
        "BloodSplatter\Textures\BloodPool_2\43.paa",
        "BloodSplatter\Textures\BloodPool_2\44.paa",
        "BloodSplatter\Textures\BloodPool_2\45.paa",
        "BloodSplatter\Textures\BloodPool_2\46.paa",
        "BloodSplatter\Textures\BloodPool_2\47.paa",
        "BloodSplatter\Textures\BloodPool_2\48.paa",
        "BloodSplatter\Textures\BloodPool_2\49.paa",
        "BloodSplatter\Textures\BloodPool_2\50.paa",
        "BloodSplatter\Textures\BloodPool_2\51.paa",
        "BloodSplatter\Textures\BloodPool_2\52.paa",
        "BloodSplatter\Textures\BloodPool_2\53.paa",
        "BloodSplatter\Textures\BloodPool_2\54.paa",
        "BloodSplatter\Textures\BloodPool_2\55.paa",
        "BloodSplatter\Textures\BloodPool_2\56.paa",
        "BloodSplatter\Textures\BloodPool_2\57.paa",
        "BloodSplatter\Textures\BloodPool_2\58.paa",
        "BloodSplatter\Textures\BloodPool_2\59.paa",
        "BloodSplatter\Textures\BloodPool_2\60.paa",
        "BloodSplatter\Textures\BloodPool_2\61.paa",
        "BloodSplatter\Textures\BloodPool_2\62.paa",
        "BloodSplatter\Textures\BloodPool_2\63.paa",
        "BloodSplatter\Textures\BloodPool_2\64.paa",
        "BloodSplatter\Textures\BloodPool_2\65.paa",
        "BloodSplatter\Textures\BloodPool_2\66.paa",
        "BloodSplatter\Textures\BloodPool_2\67.paa",
        "BloodSplatter\Textures\BloodPool_2\68.paa",
        "BloodSplatter\Textures\BloodPool_2\69.paa",
        "BloodSplatter\Textures\BloodPool_2\70.paa",
        "BloodSplatter\Textures\BloodPool_2\71.paa",
        "BloodSplatter\Textures\BloodPool_2\72.paa",
        "BloodSplatter\Textures\BloodPool_2\73.paa",
        "BloodSplatter\Textures\BloodPool_2\74.paa",
        "BloodSplatter\Textures\BloodPool_2\75.paa",
        "BloodSplatter\Textures\BloodPool_2\76.paa",
        "BloodSplatter\Textures\BloodPool_2\77.paa",
        "BloodSplatter\Textures\BloodPool_2\78.paa",
        "BloodSplatter\Textures\BloodPool_2\79.paa",
        "BloodSplatter\Textures\BloodPool_2\80.paa",
        "BloodSplatter\Textures\BloodPool_2\81.paa",
        "BloodSplatter\Textures\BloodPool_2\82.paa",
        "BloodSplatter\Textures\BloodPool_2\83.paa",
        "BloodSplatter\Textures\BloodPool_2\84.paa",
        "BloodSplatter\Textures\BloodPool_2\85.paa",
        "BloodSplatter\Textures\BloodPool_2\86.paa",
        "BloodSplatter\Textures\BloodPool_2\87.paa",
        "BloodSplatter\Textures\BloodPool_2\88.paa",
        "BloodSplatter\Textures\BloodPool_2\89.paa",
        "BloodSplatter\Textures\BloodPool_2\90.paa",
        "BloodSplatter\Textures\BloodPool_2\91.paa",
        "BloodSplatter\Textures\BloodPool_2\92.paa",
        "BloodSplatter\Textures\BloodPool_2\93.paa",
        "BloodSplatter\Textures\BloodPool_2\94.paa",
        "BloodSplatter\Textures\BloodPool_2\95.paa",
        "BloodSplatter\Textures\BloodPool_2\96.paa",
        "BloodSplatter\Textures\BloodPool_2\97.paa",
        "BloodSplatter\Textures\BloodPool_2\98.paa",
        "BloodSplatter\Textures\BloodPool_2\99.paa",
        "BloodSplatter\Textures\BloodPool_2\100.paa",
        "BloodSplatter\Textures\BloodPool_2\101.paa",
        "BloodSplatter\Textures\BloodPool_2\102.paa",
        "BloodSplatter\Textures\BloodPool_2\103.paa",
        "BloodSplatter\Textures\BloodPool_2\104.paa",
        "BloodSplatter\Textures\BloodPool_2\105.paa",
        "BloodSplatter\Textures\BloodPool_2\106.paa",
        "BloodSplatter\Textures\BloodPool_2\107.paa",
        "BloodSplatter\Textures\BloodPool_2\108.paa",
        "BloodSplatter\Textures\BloodPool_2\109.paa",
        "BloodSplatter\Textures\BloodPool_2\110.paa",
        "BloodSplatter\Textures\BloodPool_2\111.paa",
        "BloodSplatter\Textures\BloodPool_2\112.paa",
        "BloodSplatter\Textures\BloodPool_2\113.paa",
        "BloodSplatter\Textures\BloodPool_2\114.paa",
        "BloodSplatter\Textures\BloodPool_2\115.paa",
        "BloodSplatter\Textures\BloodPool_2\116.paa",
        "BloodSplatter\Textures\BloodPool_2\117.paa",
        "BloodSplatter\Textures\BloodPool_2\118.paa",
        "BloodSplatter\Textures\BloodPool_2\119.paa",
        "BloodSplatter\Textures\BloodPool_2\120.paa",
        "BloodSplatter\Textures\BloodPool_2\121.paa",
        "BloodSplatter\Textures\BloodPool_2\122.paa",
        "BloodSplatter\Textures\BloodPool_2\123.paa",
        "BloodSplatter\Textures\BloodPool_2\124.paa",
        "BloodSplatter\Textures\BloodPool_2\125.paa",
        "BloodSplatter\Textures\BloodPool_2\126.paa",
        "BloodSplatter\Textures\BloodPool_2\127.paa",
        "BloodSplatter\Textures\BloodPool_2\128.paa",
        "BloodSplatter\Textures\BloodPool_2\129.paa",
        "BloodSplatter\Textures\BloodPool_2\130.paa",
        "BloodSplatter\Textures\BloodPool_2\131.paa",
        "BloodSplatter\Textures\BloodPool_2\132.paa",
        "BloodSplatter\Textures\BloodPool_2\133.paa",
        "BloodSplatter\Textures\BloodPool_2\134.paa",
        "BloodSplatter\Textures\BloodPool_2\135.paa",
        "BloodSplatter\Textures\BloodPool_2\136.paa",
        "BloodSplatter\Textures\BloodPool_2\137.paa",
        "BloodSplatter\Textures\BloodPool_2\138.paa",
        "BloodSplatter\Textures\BloodPool_2\139.paa",
        "BloodSplatter\Textures\BloodPool_2\140.paa",
        "BloodSplatter\Textures\BloodPool_2\141.paa",
        "BloodSplatter\Textures\BloodPool_2\142.paa",
        "BloodSplatter\Textures\BloodPool_2\143.paa",
        "BloodSplatter\Textures\BloodPool_2\144.paa",
        "BloodSplatter\Textures\BloodPool_2\145.paa",
        "BloodSplatter\Textures\BloodPool_2\146.paa",
        "BloodSplatter\Textures\BloodPool_2\147.paa",
        "BloodSplatter\Textures\BloodPool_2\148.paa",
        "BloodSplatter\Textures\BloodPool_2\149.paa",
        "BloodSplatter\Textures\BloodPool_2\150.paa",
        "BloodSplatter\Textures\BloodPool_2\151.paa",
        "BloodSplatter\Textures\BloodPool_2\152.paa",
        "BloodSplatter\Textures\BloodPool_2\153.paa",
        "BloodSplatter\Textures\BloodPool_2\154.paa",
        "BloodSplatter\Textures\BloodPool_2\155.paa",
        "BloodSplatter\Textures\BloodPool_2\156.paa",
        "BloodSplatter\Textures\BloodPool_2\157.paa",
        "BloodSplatter\Textures\BloodPool_2\158.paa",
        "BloodSplatter\Textures\BloodPool_2\159.paa",
        "BloodSplatter\Textures\BloodPool_2\160.paa",
        "BloodSplatter\Textures\BloodPool_2\161.paa",
        "BloodSplatter\Textures\BloodPool_2\162.paa",
        "BloodSplatter\Textures\BloodPool_2\163.paa",
        "BloodSplatter\Textures\BloodPool_2\164.paa",
        "BloodSplatter\Textures\BloodPool_2\165.paa",
        "BloodSplatter\Textures\BloodPool_2\166.paa",
        "BloodSplatter\Textures\BloodPool_2\167.paa",
        "BloodSplatter\Textures\BloodPool_2\168.paa",
        "BloodSplatter\Textures\BloodPool_2\169.paa",
        "BloodSplatter\Textures\BloodPool_2\170.paa",
        "BloodSplatter\Textures\BloodPool_2\171.paa",
        "BloodSplatter\Textures\BloodPool_2\172.paa",
        "BloodSplatter\Textures\BloodPool_2\173.paa",
        "BloodSplatter\Textures\BloodPool_2\174.paa",
        "BloodSplatter\Textures\BloodPool_2\175.paa",
        "BloodSplatter\Textures\BloodPool_2\176.paa",
        "BloodSplatter\Textures\BloodPool_2\177.paa",
        "BloodSplatter\Textures\BloodPool_2\178.paa",
        "BloodSplatter\Textures\BloodPool_2\179.paa",
        "BloodSplatter\Textures\BloodPool_2\180.paa",
        "BloodSplatter\Textures\BloodPool_2\181.paa",
        "BloodSplatter\Textures\BloodPool_2\182.paa",
        "BloodSplatter\Textures\BloodPool_2\183.paa",
        "BloodSplatter\Textures\BloodPool_2\184.paa",
        "BloodSplatter\Textures\BloodPool_2\185.paa",
        "BloodSplatter\Textures\BloodPool_2\186.paa",
        "BloodSplatter\Textures\BloodPool_2\187.paa",
        "BloodSplatter\Textures\BloodPool_2\188.paa",
        "BloodSplatter\Textures\BloodPool_2\189.paa",
        "BloodSplatter\Textures\BloodPool_2\190.paa",
        "BloodSplatter\Textures\BloodPool_2\191.paa",
        "BloodSplatter\Textures\BloodPool_2\192.paa",
        "BloodSplatter\Textures\BloodPool_2\193.paa",
        "BloodSplatter\Textures\BloodPool_2\194.paa",
        "BloodSplatter\Textures\BloodPool_2\195.paa",
        "BloodSplatter\Textures\BloodPool_2\196.paa",
        "BloodSplatter\Textures\BloodPool_2\197.paa",
        "BloodSplatter\Textures\BloodPool_2\198.paa",
        "BloodSplatter\Textures\BloodPool_2\199.paa",
        "BloodSplatter\Textures\BloodPool_2\200.paa",
        "BloodSplatter\Textures\BloodPool_2\201.paa",
        "BloodSplatter\Textures\BloodPool_2\202.paa",
        "BloodSplatter\Textures\BloodPool_2\203.paa",
        "BloodSplatter\Textures\BloodPool_2\204.paa",
        "BloodSplatter\Textures\BloodPool_2\205.paa",
        "BloodSplatter\Textures\BloodPool_2\206.paa",
        "BloodSplatter\Textures\BloodPool_2\207.paa",
        "BloodSplatter\Textures\BloodPool_2\208.paa",
        "BloodSplatter\Textures\BloodPool_2\209.paa",
        "BloodSplatter\Textures\BloodPool_2\210.paa",
        "BloodSplatter\Textures\BloodPool_2\211.paa",
        "BloodSplatter\Textures\BloodPool_2\212.paa",
        "BloodSplatter\Textures\BloodPool_2\213.paa",
        "BloodSplatter\Textures\BloodPool_2\214.paa",
        "BloodSplatter\Textures\BloodPool_2\215.paa",
        "BloodSplatter\Textures\BloodPool_2\216.paa",
        "BloodSplatter\Textures\BloodPool_2\217.paa",
        "BloodSplatter\Textures\BloodPool_2\218.paa",
        "BloodSplatter\Textures\BloodPool_2\219.paa",
        "BloodSplatter\Textures\BloodPool_2\220.paa",
        "BloodSplatter\Textures\BloodPool_2\221.paa",
        "BloodSplatter\Textures\BloodPool_2\222.paa",
        "BloodSplatter\Textures\BloodPool_2\223.paa",
        "BloodSplatter\Textures\BloodPool_2\224.paa",
        "BloodSplatter\Textures\BloodPool_2\225.paa",
        "BloodSplatter\Textures\BloodPool_2\226.paa",
        "BloodSplatter\Textures\BloodPool_2\227.paa",
        "BloodSplatter\Textures\BloodPool_2\228.paa",
        "BloodSplatter\Textures\BloodPool_2\229.paa",
        "BloodSplatter\Textures\BloodPool_2\230.paa",
        "BloodSplatter\Textures\BloodPool_2\231.paa"
    ]
]];
BloodLust_SprayTextures = profileNamespace getVariable ["BloodLust_SprayTextures",
[
    [
        "BloodSplatter\Textures\Spray_1\1.paa",
        "BloodSplatter\Textures\Spray_1\2.paa",
        "BloodSplatter\Textures\Spray_1\3.paa",
        "BloodSplatter\Textures\Spray_1\4.paa",
        "BloodSplatter\Textures\Spray_1\5.paa",
        "BloodSplatter\Textures\Spray_1\6.paa",
        "BloodSplatter\Textures\Spray_1\7.paa",
        "BloodSplatter\Textures\Spray_1\8.paa",
        "BloodSplatter\Textures\Spray_1\9.paa",
        "BloodSplatter\Textures\Spray_1\10.paa",
        "BloodSplatter\Textures\Spray_1\11.paa",
        "BloodSplatter\Textures\Spray_1\12.paa",
        "BloodSplatter\Textures\Spray_1\13.paa",
        "BloodSplatter\Textures\Spray_1\14.paa",
        "BloodSplatter\Textures\Spray_1\15.paa",
        "BloodSplatter\Textures\Spray_1\16.paa",
        "BloodSplatter\Textures\Spray_1\17.paa",
        "BloodSplatter\Textures\Spray_1\18.paa",
        "BloodSplatter\Textures\Spray_1\19.paa",
        "BloodSplatter\Textures\Spray_1\20.paa",
        "BloodSplatter\Textures\Spray_1\21.paa",
        "BloodSplatter\Textures\Spray_1\22.paa",
        "BloodSplatter\Textures\Spray_1\23.paa",
        "BloodSplatter\Textures\Spray_1\24.paa",
        "BloodSplatter\Textures\Spray_1\25.paa",
        "BloodSplatter\Textures\Spray_1\26.paa",
        "BloodSplatter\Textures\Spray_1\27.paa",
        "BloodSplatter\Textures\Spray_1\28.paa",
        "BloodSplatter\Textures\Spray_1\29.paa",
        "BloodSplatter\Textures\Spray_1\30.paa",
        "BloodSplatter\Textures\Spray_1\31.paa",
        "BloodSplatter\Textures\Spray_1\32.paa",
        "BloodSplatter\Textures\Spray_1\33.paa",
        "BloodSplatter\Textures\Spray_1\34.paa",
        "BloodSplatter\Textures\Spray_1\35.paa",
        "BloodSplatter\Textures\Spray_1\36.paa",
        "BloodSplatter\Textures\Spray_1\37.paa",
        "BloodSplatter\Textures\Spray_1\38.paa",
        "BloodSplatter\Textures\Spray_1\39.paa",
        "BloodSplatter\Textures\Spray_1\40.paa",
        "BloodSplatter\Textures\Spray_1\41.paa",
        "BloodSplatter\Textures\Spray_1\42.paa",
        "BloodSplatter\Textures\Spray_1\43.paa",
        "BloodSplatter\Textures\Spray_1\44.paa",
        "BloodSplatter\Textures\Spray_1\45.paa",
        "BloodSplatter\Textures\Spray_1\46.paa",
        "BloodSplatter\Textures\Spray_1\47.paa",
        "BloodSplatter\Textures\Spray_1\48.paa",
        "BloodSplatter\Textures\Spray_1\49.paa",
        "BloodSplatter\Textures\Spray_1\50.paa",
        "BloodSplatter\Textures\Spray_1\51.paa",
        "BloodSplatter\Textures\Spray_1\52.paa",
        "BloodSplatter\Textures\Spray_1\53.paa",
        "BloodSplatter\Textures\Spray_1\54.paa",
        "BloodSplatter\Textures\Spray_1\55.paa",
        "BloodSplatter\Textures\Spray_1\56.paa"
    ],
    [
        "BloodSplatter\Textures\Spray_2\1.paa",
        "BloodSplatter\Textures\Spray_2\2.paa",
        "BloodSplatter\Textures\Spray_2\3.paa",
        "BloodSplatter\Textures\Spray_2\4.paa",
        "BloodSplatter\Textures\Spray_2\5.paa",
        "BloodSplatter\Textures\Spray_2\6.paa",
        "BloodSplatter\Textures\Spray_2\7.paa",
        "BloodSplatter\Textures\Spray_2\8.paa",
        "BloodSplatter\Textures\Spray_2\9.paa",
        "BloodSplatter\Textures\Spray_2\10.paa",
        "BloodSplatter\Textures\Spray_2\11.paa",
        "BloodSplatter\Textures\Spray_2\12.paa",
        "BloodSplatter\Textures\Spray_2\13.paa",
        "BloodSplatter\Textures\Spray_2\14.paa",
        "BloodSplatter\Textures\Spray_2\15.paa",
        "BloodSplatter\Textures\Spray_2\16.paa",
        "BloodSplatter\Textures\Spray_2\17.paa",
        "BloodSplatter\Textures\Spray_2\18.paa",
        "BloodSplatter\Textures\Spray_2\19.paa",
        "BloodSplatter\Textures\Spray_2\20.paa",
        "BloodSplatter\Textures\Spray_2\21.paa",
        "BloodSplatter\Textures\Spray_2\22.paa",
        "BloodSplatter\Textures\Spray_2\23.paa",
        "BloodSplatter\Textures\Spray_2\24.paa",
        "BloodSplatter\Textures\Spray_2\25.paa",
        "BloodSplatter\Textures\Spray_2\26.paa",
        "BloodSplatter\Textures\Spray_2\27.paa"
    ],
    [
        "BloodSplatter\Textures\Spray_3\1.paa",
        "BloodSplatter\Textures\Spray_3\2.paa",
        "BloodSplatter\Textures\Spray_3\3.paa",
        "BloodSplatter\Textures\Spray_3\4.paa",
        "BloodSplatter\Textures\Spray_3\5.paa",
        "BloodSplatter\Textures\Spray_3\6.paa",
        "BloodSplatter\Textures\Spray_3\7.paa",
        "BloodSplatter\Textures\Spray_3\8.paa",
        "BloodSplatter\Textures\Spray_3\9.paa",
        "BloodSplatter\Textures\Spray_3\10.paa",
        "BloodSplatter\Textures\Spray_3\11.paa",
        "BloodSplatter\Textures\Spray_3\12.paa",
        "BloodSplatter\Textures\Spray_3\13.paa",
        "BloodSplatter\Textures\Spray_3\14.paa",
        "BloodSplatter\Textures\Spray_3\15.paa",
        "BloodSplatter\Textures\Spray_3\16.paa",
        "BloodSplatter\Textures\Spray_3\17.paa",
        "BloodSplatter\Textures\Spray_3\18.paa",
        "BloodSplatter\Textures\Spray_3\19.paa",
        "BloodSplatter\Textures\Spray_3\20.paa",
        "BloodSplatter\Textures\Spray_3\21.paa",
        "BloodSplatter\Textures\Spray_3\22.paa",
        "BloodSplatter\Textures\Spray_3\23.paa",
        "BloodSplatter\Textures\Spray_3\24.paa",
        "BloodSplatter\Textures\Spray_3\25.paa",
        "BloodSplatter\Textures\Spray_3\26.paa",
        "BloodSplatter\Textures\Spray_3\27.paa",
        "BloodSplatter\Textures\Spray_3\28.paa",
        "BloodSplatter\Textures\Spray_3\29.paa",
        "BloodSplatter\Textures\Spray_3\30.paa",
        "BloodSplatter\Textures\Spray_3\31.paa",
        "BloodSplatter\Textures\Spray_3\32.paa"
    ],
    [
        "BloodSplatter\Textures\Spray_4\1.paa",
        "BloodSplatter\Textures\Spray_4\2.paa",
        "BloodSplatter\Textures\Spray_4\3.paa",
        "BloodSplatter\Textures\Spray_4\4.paa",
        "BloodSplatter\Textures\Spray_4\5.paa",
        "BloodSplatter\Textures\Spray_4\6.paa",
        "BloodSplatter\Textures\Spray_4\7.paa",
        "BloodSplatter\Textures\Spray_4\8.paa",
        "BloodSplatter\Textures\Spray_4\9.paa",
        "BloodSplatter\Textures\Spray_4\10.paa",
        "BloodSplatter\Textures\Spray_4\11.paa",
        "BloodSplatter\Textures\Spray_4\12.paa",
        "BloodSplatter\Textures\Spray_4\13.paa",
        "BloodSplatter\Textures\Spray_4\14.paa",
        "BloodSplatter\Textures\Spray_4\15.paa",
        "BloodSplatter\Textures\Spray_4\16.paa",
        "BloodSplatter\Textures\Spray_4\17.paa",
        "BloodSplatter\Textures\Spray_4\18.paa",
        "BloodSplatter\Textures\Spray_4\19.paa",
        "BloodSplatter\Textures\Spray_4\20.paa",
        "BloodSplatter\Textures\Spray_4\21.paa",
        "BloodSplatter\Textures\Spray_4\22.paa",
        "BloodSplatter\Textures\Spray_4\23.paa",
        "BloodSplatter\Textures\Spray_4\24.paa",
        "BloodSplatter\Textures\Spray_4\25.paa",
        "BloodSplatter\Textures\Spray_4\26.paa",
        "BloodSplatter\Textures\Spray_4\27.paa",
        "BloodSplatter\Textures\Spray_4\28.paa",
        "BloodSplatter\Textures\Spray_4\29.paa",
        "BloodSplatter\Textures\Spray_4\30.paa",
        "BloodSplatter\Textures\Spray_4\31.paa",
        "BloodSplatter\Textures\Spray_4\32.paa",
        "BloodSplatter\Textures\Spray_4\33.paa",
        "BloodSplatter\Textures\Spray_4\34.paa",
        "BloodSplatter\Textures\Spray_4\35.paa",
        "BloodSplatter\Textures\Spray_4\36.paa",
        "BloodSplatter\Textures\Spray_4\37.paa",
        "BloodSplatter\Textures\Spray_4\38.paa",
        "BloodSplatter\Textures\Spray_4\39.paa",
        "BloodSplatter\Textures\Spray_4\40.paa",
        "BloodSplatter\Textures\Spray_4\41.paa",
        "BloodSplatter\Textures\Spray_4\42.paa",
        "BloodSplatter\Textures\Spray_4\43.paa",
        "BloodSplatter\Textures\Spray_4\44.paa",
        "BloodSplatter\Textures\Spray_4\45.paa",
        "BloodSplatter\Textures\Spray_4\46.paa",
        "BloodSplatter\Textures\Spray_4\47.paa",
        "BloodSplatter\Textures\Spray_4\48.paa",
        "BloodSplatter\Textures\Spray_4\49.paa",
        "BloodSplatter\Textures\Spray_4\50.paa",
        "BloodSplatter\Textures\Spray_4\51.paa",
        "BloodSplatter\Textures\Spray_4\52.paa",
        "BloodSplatter\Textures\Spray_4\53.paa",
        "BloodSplatter\Textures\Spray_4\54.paa",
        "BloodSplatter\Textures\Spray_4\55.paa",
        "BloodSplatter\Textures\Spray_4\56.paa",
        "BloodSplatter\Textures\Spray_4\57.paa",
        "BloodSplatter\Textures\Spray_4\58.paa",
        "BloodSplatter\Textures\Spray_4\59.paa",
        "BloodSplatter\Textures\Spray_4\60.paa",
        "BloodSplatter\Textures\Spray_4\61.paa",
        "BloodSplatter\Textures\Spray_4\62.paa",
        "BloodSplatter\Textures\Spray_4\63.paa",
        "BloodSplatter\Textures\Spray_4\64.paa",
        "BloodSplatter\Textures\Spray_4\65.paa",
        "BloodSplatter\Textures\Spray_4\66.paa",
        "BloodSplatter\Textures\Spray_4\67.paa",
        "BloodSplatter\Textures\Spray_4\68.paa"
    ]
]];
BloodLust_BleedTextures = profileNamespace getVariable ["BloodLust_BleedTextures",
[
    "BloodSplatter\Textures\Bleed\bleed_1.paa",
    "BloodSplatter\Textures\Bleed\bleed_2.paa",
    "BloodSplatter\Textures\Bleed\bleed_3.paa",
    "BloodSplatter\Textures\Bleed\bleed_4.paa",
    "BloodSplatter\Textures\Bleed\bleed_5.paa",
    "BloodSplatter\Textures\Bleed\bleed_6.paa",
    "BloodSplatter\Textures\Bleed\bleed_7.paa",
    "BloodSplatter\Textures\Bleed\bleed_8.paa",
    "BloodSplatter\Textures\Bleed\bleed_9.paa",
    "BloodSplatter\Textures\Bleed\bleed_10.paa",
    "BloodSplatter\Textures\Bleed\bleed_11.paa",
    "BloodSplatter\Textures\Bleed\bleed_12.paa"
]];
BloodLust_SmearTextures = profileNamespace getVariable ["BloodLust_SmearTextures",
[
    "BloodSplatter\Textures\Smear\smear_1.paa",
    "BloodSplatter\Textures\Smear\smear_2.paa",
    "BloodSplatter\Textures\Smear\smear_3.paa",
    "BloodSplatter\Textures\Smear\smear_4.paa",
    "BloodSplatter\Textures\Smear\smear_5.paa",
    "BloodSplatter\Textures\Smear\smear_6.paa",
    "BloodSplatter\Textures\Smear\smear_7.paa",
    "BloodSplatter\Textures\Smear\smear_8.paa"
]];
BloodLust_BleedSounds = profileNamespace getVariable ["BloodLust_BleedSounds",
[
    "BloodSplatter\Audio\blooddrip_1.ogg",
    "BloodSplatter\Audio\blooddrip_2.ogg",
    "BloodSplatter\Audio\blooddrip_3.ogg"
]];
BloodLust_HeadGibClassnames = profileNamespace getVariable ["BloodLust_HeadGibClassnames",
[

]];
BloodLust_Spine1GibClassnames = profileNamespace getVariable ["BloodLust_Spine1GibClassnames",
[

]];
BloodLust_Spine2GibClassnames = profileNamespace getVariable ["BloodLust_Spine2GibClassnames",
[

]];
BloodLust_Spine3GibClassnames = profileNamespace getVariable ["BloodLust_Spine3GibClassnames",
[

]];
BloodLust_BodyGibClassnames = profileNamespace getVariable ["BloodLust_BodyGibClassnames",
[

]];
BloodLust_ArmGibClassnames = profileNamespace getVariable ["BloodLust_ArmGibClassnames",
[

]];
BloodLust_LegGibClassnames = profileNamespace getVariable ["BloodLust_LegGibClassnames",
[

]];
BloodLust_VaporizationGibClassnames = profileNamespace getVariable ["BloodLust_VaporizationGibClassnames", //[gib set index for algorithmic purposes, classname, initial gib count this collection is copied by BloodLust_VaporizeUnit for simplicity, max emmisions of this gib per vaporization]
[
    [0, "BloodSplatter_LeftHand", 0, 1],
    [1, "BloodSplatter_LeftLowerArm", 0, 1],
    [2, "BloodSplatter_LeftLowerLegAndFoot", 0, 1],
    [3, "BloodSplatter_LeftUpperArm", 0, 1],
    [4, "BloodSplatter_LeftUpperLeg", 0, 1],
    [5, "BloodSplatter_Pelvis", 0, 1],
    [6, "BloodSplatter_RightFoot", 0, 1],
    [7, "BloodSplatter_RightHand", 0, 1],
    [8, "BloodSplatter_RightIndexFinger", 0, 1],
    [9, "BloodSplatter_RightLowerArm", 0, 1],
    [10, "BloodSplatter_RightLowerLeg", 0, 1],
    [11, "BloodSplatter_Torso", 0, 1],
    [12, "BloodSplatter_RightMiddleFinger", 0, 1],
    [13, "BloodSplatter_RightPinkyFinger", 0, 1],
    [14, "BloodSplatter_RightRingFinger", 0, 1],
    [15, "BloodSplatter_RightThumb", 0, 1],
    [16, "BloodSplatter_RightUpperArm", 0, 1],
    [17, "BloodSplatter_RightUpperLeg", 0, 1]
]];
